spring.application.name=tpip_backend
server.port=8084

# ================= DATABASE configuration=================
spring.datasource.url=jdbc:postgresql://localhost:5432/tpip_db_v2
spring.datasource.username=rahma
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA configuration =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
